#! /bin/sh

## Wallpaper
feh --bg-scale ~/.dotfiles/.config/feh/wallpaper.png

## Polybar
# $HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d dev lab tune chat 5 6 7 8 9

bspc config border_width         3
bspc config window_gap          5
bspc config normal_border_color "#14021c"
bspc config focused_border_color "#f7af16"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Nemo state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
